/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 02 19:01:28 GMT 2018
 */

package org.mozilla.javascript.tools.shell;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.OutputStream;
import java.io.PipedInputStream;
import java.io.SequenceInputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.junit.runner.RunWith;
import org.mozilla.javascript.tools.shell.PipeThread;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PipeThread_ESTest extends PipeThread_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(pipedInputStream0, pipedInputStream0);
      PipeThread pipeThread0 = new PipeThread(true, sequenceInputStream0, (OutputStream) null);
      pipeThread0.run();
      assertTrue(pipeThread0.isDaemon());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream(1402);
      MockPrintStream mockPrintStream0 = new MockPrintStream("~`kKr \"t.j!(6_*[:");
      PipeThread pipeThread0 = new PipeThread(false, pipedInputStream0, mockPrintStream0);
      // Undeclared exception!
      try { 
        pipeThread0.run();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Wrapped java.io.IOException: Pipe not connected
         //
         verifyException("org.mozilla.javascript.Context", e);
      }
  }
}
