/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 01 05:26:48 GMT 2018
 */

package org.mozilla.javascript;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.mozilla.javascript.ScriptStackElement;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ScriptStackElement_ESTest extends ScriptStackElement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ScriptStackElement scriptStackElement0 = new ScriptStackElement("", "e", (-1375));
      String string0 = scriptStackElement0.toString();
      assertEquals("e()@", string0);
      assertEquals((-1375), scriptStackElement0.lineNumber);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ScriptStackElement scriptStackElement0 = new ScriptStackElement("", (String) null, 0);
      StringBuilder stringBuilder0 = new StringBuilder("");
      scriptStackElement0.renderV8Style(stringBuilder0);
      assertEquals("    at :0:0", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ScriptStackElement scriptStackElement0 = new ScriptStackElement(" (", " (", 0);
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) " (");
      scriptStackElement0.renderMozillaStyle(stringBuilder0);
      assertEquals(" ( (()@ (:0", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ScriptStackElement scriptStackElement0 = new ScriptStackElement(" (", " (", 0);
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) " (");
      scriptStackElement0.renderJavaStyle(stringBuilder0);
      assertEquals(" (\tat  (:0 ( ()", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ScriptStackElement scriptStackElement0 = new ScriptStackElement(" (", " (", 0);
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) " (");
      scriptStackElement0.renderV8Style(stringBuilder0);
      assertEquals(" (    at  ( ( (:0:0)", stringBuilder0.toString());
  }
}
