/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 01 05:15:34 GMT 2018
 */

package org.mozilla.javascript;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.function.Consumer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.mozilla.javascript.ScriptableObject;
import org.mozilla.javascript.ThreadSafeSlotMapContainer;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ThreadSafeSlotMapContainer_ESTest extends ThreadSafeSlotMapContainer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ThreadSafeSlotMapContainer threadSafeSlotMapContainer0 = new ThreadSafeSlotMapContainer(399);
      threadSafeSlotMapContainer0.readLock();
      threadSafeSlotMapContainer0.unlockRead(257L);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ThreadSafeSlotMapContainer threadSafeSlotMapContainer0 = new ThreadSafeSlotMapContainer(3999);
      int int0 = threadSafeSlotMapContainer0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ThreadSafeSlotMapContainer threadSafeSlotMapContainer0 = new ThreadSafeSlotMapContainer(77);
      Object object0 = new Object();
      threadSafeSlotMapContainer0.remove(object0, 77);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ThreadSafeSlotMapContainer threadSafeSlotMapContainer0 = new ThreadSafeSlotMapContainer(3999);
      Object object0 = new Object();
      ScriptableObject.Slot scriptableObject_Slot0 = threadSafeSlotMapContainer0.query(object0, 2079);
      assertNull(scriptableObject_Slot0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ThreadSafeSlotMapContainer threadSafeSlotMapContainer0 = new ThreadSafeSlotMapContainer(3999);
      threadSafeSlotMapContainer0.readLock();
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      threadSafeSlotMapContainer0.forEach(consumer0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ThreadSafeSlotMapContainer threadSafeSlotMapContainer0 = new ThreadSafeSlotMapContainer(3999);
      boolean boolean0 = threadSafeSlotMapContainer0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ThreadSafeSlotMapContainer threadSafeSlotMapContainer0 = new ThreadSafeSlotMapContainer(3999);
      threadSafeSlotMapContainer0.readLock();
      int int0 = threadSafeSlotMapContainer0.dirtySize();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ThreadSafeSlotMapContainer threadSafeSlotMapContainer0 = new ThreadSafeSlotMapContainer(1);
      ScriptableObject.SlotAccess scriptableObject_SlotAccess0 = ScriptableObject.SlotAccess.MODIFY_CONST;
      ScriptableObject.Slot scriptableObject_Slot0 = threadSafeSlotMapContainer0.get("E_]xl?KtB+</q", 1, scriptableObject_SlotAccess0);
      threadSafeSlotMapContainer0.addSlot(scriptableObject_Slot0);
      Object object0 = new Object();
      threadSafeSlotMapContainer0.get(object0, 1, scriptableObject_SlotAccess0);
      Integer integer0 = new Integer(791);
      // Undeclared exception!
      threadSafeSlotMapContainer0.get(integer0, 0, scriptableObject_SlotAccess0);
  }
}
