/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 01 20:47:31 GMT 2018
 */

package org.mozilla.javascript.tools.debugger;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.event.KeyEvent;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JRadioButton;
import javax.swing.MenuElement;
import javax.swing.MenuSelectionManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.MenuKeyEvent;
import javax.swing.text.AbstractDocument;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.PlainDocument;
import javax.swing.text.StyleContext;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.mozilla.javascript.tools.debugger.EvalTextArea;
import org.mozilla.javascript.tools.debugger.SwingGui;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EvalTextArea_ESTest extends EvalTextArea_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      EvalTextArea evalTextArea0 = new EvalTextArea((SwingGui) null);
      evalTextArea0.write("Dr1v^4k+S)OgRB%M{");
      assertTrue(evalTextArea0.getFocusTraversalKeysEnabled());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      EvalTextArea evalTextArea0 = new EvalTextArea((SwingGui) null);
      StyleContext styleContext0 = StyleContext.getDefaultStyleContext();
      DefaultStyledDocument defaultStyledDocument0 = new DefaultStyledDocument(styleContext0);
      DocumentEvent.EventType documentEvent_EventType0 = DocumentEvent.EventType.INSERT;
      AbstractDocument.DefaultDocumentEvent abstractDocument_DefaultDocumentEvent0 = defaultStyledDocument0.new DefaultDocumentEvent(0, (-35), documentEvent_EventType0);
      evalTextArea0.insertUpdate(abstractDocument_DefaultDocumentEvent0);
      KeyEvent keyEvent0 = new KeyEvent(evalTextArea0, (-35), (-35), (-35), 10, '>');
      // Undeclared exception!
      try { 
        evalTextArea0.keyPressed(keyEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.mozilla.javascript.tools.debugger.EvalTextArea", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      EvalTextArea evalTextArea0 = new EvalTextArea((SwingGui) null);
      PlainDocument plainDocument0 = new PlainDocument();
      AbstractDocument.DefaultDocumentEvent abstractDocument_DefaultDocumentEvent0 = plainDocument0.new DefaultDocumentEvent((-175), 2869, (DocumentEvent.EventType) null);
      evalTextArea0.removeUpdate(abstractDocument_DefaultDocumentEvent0);
      assertFalse(evalTextArea0.isFocusCycleRoot());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      EvalTextArea evalTextArea0 = new EvalTextArea((SwingGui) null);
      DefaultStyledDocument defaultStyledDocument0 = new DefaultStyledDocument();
      DocumentEvent.EventType documentEvent_EventType0 = DocumentEvent.EventType.INSERT;
      AbstractDocument.DefaultDocumentEvent abstractDocument_DefaultDocumentEvent0 = defaultStyledDocument0.new DefaultDocumentEvent((-698), (-698), documentEvent_EventType0);
      evalTextArea0.removeUpdate(abstractDocument_DefaultDocumentEvent0);
      assertFalse(evalTextArea0.isFocusCycleRoot());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      EvalTextArea evalTextArea0 = new EvalTextArea((SwingGui) null);
      evalTextArea0.postUpdateUI();
      KeyEvent keyEvent0 = new KeyEvent(evalTextArea0, (-1346), (-1346), (-1346), (-1346), '\b');
      evalTextArea0.keyTyped(keyEvent0);
      assertTrue(keyEvent0.isConsumed());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EvalTextArea evalTextArea0 = new EvalTextArea((SwingGui) null);
      MenuElement[] menuElementArray0 = new MenuElement[0];
      MenuSelectionManager menuSelectionManager0 = MenuSelectionManager.defaultManager();
      MenuKeyEvent menuKeyEvent0 = new MenuKeyEvent(evalTextArea0, (-2968), (-2968), (-2968), (-238), 'S', menuElementArray0, menuSelectionManager0);
      evalTextArea0.keyReleased(menuKeyEvent0);
      assertFalse(menuKeyEvent0.isControlDown());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      EvalTextArea evalTextArea0 = new EvalTextArea((SwingGui) null);
      JCheckBoxMenuItem jCheckBoxMenuItem0 = new JCheckBoxMenuItem("Primitive ");
      MenuElement[] menuElementArray0 = new MenuElement[6];
      MenuSelectionManager menuSelectionManager0 = MenuSelectionManager.defaultManager();
      MenuKeyEvent menuKeyEvent0 = new MenuKeyEvent(jCheckBoxMenuItem0, 40, 40, 40, 40, '\u0084', menuElementArray0, menuSelectionManager0);
      evalTextArea0.keyPressed(menuKeyEvent0);
      assertTrue(menuKeyEvent0.isConsumed());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      EvalTextArea evalTextArea0 = new EvalTextArea((SwingGui) null);
      JCheckBoxMenuItem jCheckBoxMenuItem0 = new JCheckBoxMenuItem("anon|ymous");
      MenuElement[] menuElementArray0 = new MenuElement[6];
      MenuSelectionManager menuSelectionManager0 = new MenuSelectionManager();
      MenuKeyEvent menuKeyEvent0 = new MenuKeyEvent(jCheckBoxMenuItem0, 38, 38, 38, 38, 'n', menuElementArray0, menuSelectionManager0);
      evalTextArea0.keyPressed(menuKeyEvent0);
      assertTrue(menuKeyEvent0.isConsumed());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      JRadioButton jRadioButton0 = new JRadioButton((String) null);
      KeyEvent keyEvent0 = new KeyEvent(jRadioButton0, (byte) (-86), 1592L, (byte) (-86), 10, 'P');
      EvalTextArea evalTextArea0 = new EvalTextArea((SwingGui) null);
      // Undeclared exception!
      try { 
        evalTextArea0.keyPressed(keyEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.mozilla.javascript.tools.debugger.EvalTextArea", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EvalTextArea evalTextArea0 = new EvalTextArea((SwingGui) null);
      DefaultStyledDocument defaultStyledDocument0 = new DefaultStyledDocument();
      DocumentEvent.EventType documentEvent_EventType0 = DocumentEvent.EventType.INSERT;
      AbstractDocument.DefaultDocumentEvent abstractDocument_DefaultDocumentEvent0 = defaultStyledDocument0.new DefaultDocumentEvent(0, (-35), documentEvent_EventType0);
      evalTextArea0.insertUpdate(abstractDocument_DefaultDocumentEvent0);
      KeyEvent keyEvent0 = new KeyEvent(evalTextArea0, (-35), (-35), 0, 36, 'K');
      // Undeclared exception!
      try { 
        evalTextArea0.keyPressed(keyEvent0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // bad position: -33
         //
         verifyException("javax.swing.text.JTextComponent", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      EvalTextArea evalTextArea0 = new EvalTextArea((SwingGui) null);
      MenuElement[] menuElementArray0 = new MenuElement[10];
      MenuSelectionManager menuSelectionManager0 = new MenuSelectionManager();
      MenuKeyEvent menuKeyEvent0 = new MenuKeyEvent(evalTextArea0, 'E', 'E', 'E', 36, 'E', menuElementArray0, menuSelectionManager0);
      evalTextArea0.keyTyped(menuKeyEvent0);
      evalTextArea0.keyPressed(menuKeyEvent0);
      assertTrue(menuKeyEvent0.isConsumed());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EvalTextArea evalTextArea0 = new EvalTextArea((SwingGui) null);
      MenuElement[] menuElementArray0 = new MenuElement[7];
      MenuSelectionManager menuSelectionManager0 = MenuSelectionManager.defaultManager();
      MenuKeyEvent menuKeyEvent0 = new MenuKeyEvent(evalTextArea0, 'w', 'w', 8, 8, 'w', menuElementArray0, menuSelectionManager0);
      evalTextArea0.keyTyped(menuKeyEvent0);
      evalTextArea0.keyPressed(menuKeyEvent0);
      assertTrue(menuKeyEvent0.isConsumed());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      EvalTextArea evalTextArea0 = new EvalTextArea((SwingGui) null);
      DefaultStyledDocument defaultStyledDocument0 = new DefaultStyledDocument();
      DocumentEvent.EventType documentEvent_EventType0 = DocumentEvent.EventType.INSERT;
      AbstractDocument.DefaultDocumentEvent abstractDocument_DefaultDocumentEvent0 = defaultStyledDocument0.new DefaultDocumentEvent((-791), (-791), documentEvent_EventType0);
      evalTextArea0.insertUpdate(abstractDocument_DefaultDocumentEvent0);
      KeyEvent keyEvent0 = new KeyEvent(evalTextArea0, (-791), (-791), (-791), 36, 'B');
      // Undeclared exception!
      try { 
        evalTextArea0.keyPressed(keyEvent0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // bad position: -789
         //
         verifyException("javax.swing.text.JTextComponent", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      EvalTextArea evalTextArea0 = new EvalTextArea((SwingGui) null);
      StyleContext styleContext0 = StyleContext.getDefaultStyleContext();
      DefaultStyledDocument defaultStyledDocument0 = new DefaultStyledDocument(styleContext0);
      DocumentEvent.EventType documentEvent_EventType0 = DocumentEvent.EventType.INSERT;
      AbstractDocument.DefaultDocumentEvent abstractDocument_DefaultDocumentEvent0 = defaultStyledDocument0.new DefaultDocumentEvent(44, 354, documentEvent_EventType0);
      evalTextArea0.changedUpdate(abstractDocument_DefaultDocumentEvent0);
      assertFalse(evalTextArea0.isFocusTraversalPolicySet());
  }
}
