/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 01 08:50:19 GMT 2018
 */

package org.mozilla.classfile;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.mozilla.classfile.ClassFileField;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ClassFileField_ESTest extends ClassFileField_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ClassFileField classFileField0 = new ClassFileField((short)3289, (short)1, (short)778);
      byte[] byteArray0 = new byte[17];
      classFileField0.setAttributes((byte)94, (short)0, (short) (-2429), (byte)94);
      int int0 = classFileField0.write(byteArray0, 0);
      assertEquals(16, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ClassFileField classFileField0 = new ClassFileField((short)6, (short)6, (short)1);
      byte[] byteArray0 = new byte[8];
      int int0 = classFileField0.write(byteArray0, (byte)0);
      assertEquals(8, int0);
      assertArrayEquals(new byte[] {(byte)0, (byte)1, (byte)0, (byte)6, (byte)0, (byte)6, (byte)0, (byte)0}, byteArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ClassFileField classFileField0 = new ClassFileField((short)1716, (short)1716, (short) (-3664));
      classFileField0.setAttributes((short)0, (short)0, (short)1, (short)0);
      int int0 = classFileField0.getWriteSize();
      assertEquals(16, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ClassFileField classFileField0 = new ClassFileField((short)1716, (short)1716, (short) (-3664));
      int int0 = classFileField0.getWriteSize();
      assertEquals(8, int0);
  }
}
