/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 02 03:07:46 GMT 2018
 */

package org.mozilla.javascript;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.mozilla.javascript.IdFunctionObjectES6;
import org.mozilla.javascript.NativeBoolean;
import org.mozilla.javascript.NativeJavaTopPackage;
import org.mozilla.javascript.Scriptable;
import org.mozilla.javascript.ScriptableObject;
import org.mozilla.javascript.typedarrays.NativeArrayBuffer;
import org.mozilla.javascript.typedarrays.NativeInt32Array;
import org.mozilla.javascript.typedarrays.NativeUint8ClampedArray;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IdFunctionObjectES6_ESTest extends IdFunctionObjectES6_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NativeBoolean nativeBoolean0 = new NativeBoolean(true);
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      NativeJavaTopPackage nativeJavaTopPackage0 = new NativeJavaTopPackage(classLoader0);
      IdFunctionObjectES6 idFunctionObjectES6_0 = new IdFunctionObjectES6(nativeBoolean0, nativeJavaTopPackage0, 2, "AZFKx;rZ\"wW$", 2, nativeJavaTopPackage0);
      Object object0 = new Object();
      idFunctionObjectES6_0.setInstanceIdValue(2, object0);
      assertEquals(2, idFunctionObjectES6_0.getLength());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NativeArrayBuffer nativeArrayBuffer0 = NativeArrayBuffer.EMPTY_BUFFER;
      NativeInt32Array nativeInt32Array0 = new NativeInt32Array(3);
      Class<Object> class0 = Object.class;
      // Undeclared exception!
      try { 
        ScriptableObject.getTypedProperty((Scriptable) nativeInt32Array0, "length", class0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.mozilla.javascript.NativeJavaObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NativeUint8ClampedArray nativeUint8ClampedArray0 = new NativeUint8ClampedArray();
      IdFunctionObjectES6 idFunctionObjectES6_0 = new IdFunctionObjectES6(nativeUint8ClampedArray0, nativeUint8ClampedArray0, 2, "si{R", 2, nativeUint8ClampedArray0);
      Object[] objectArray0 = idFunctionObjectES6_0.getAllIds();
      idFunctionObjectES6_0.delete("length");
      // Undeclared exception!
      try { 
        ScriptableObject.callMethod((Scriptable) idFunctionObjectES6_0, "length", objectArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // TypeError: java.lang.String@0000000008 is not a function, it is function.
         //
         verifyException("org.mozilla.javascript.ScriptRuntime", e);
      }
  }
}
