/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 02 00:44:06 GMT 2018
 */

package org.mozilla.javascript;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.mozilla.javascript.Context;
import org.mozilla.javascript.ContextFactory;
import org.mozilla.javascript.NativeArrayIterator;
import org.mozilla.javascript.NativeContinuation;
import org.mozilla.javascript.ScriptableObject;
import org.mozilla.javascript.typedarrays.NativeArrayBuffer;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NativeArrayIterator_ESTest extends NativeArrayIterator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NativeContinuation nativeContinuation0 = new NativeContinuation();
      NativeArrayIterator nativeArrayIterator0 = new NativeArrayIterator(nativeContinuation0, nativeContinuation0);
      ContextFactory contextFactory0 = new ContextFactory();
      Context context0 = contextFactory0.enterContext();
      Object object0 = nativeArrayIterator0.nextValue(context0, nativeContinuation0);
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NativeArrayBuffer nativeArrayBuffer0 = new NativeArrayBuffer(0);
      NativeArrayIterator nativeArrayIterator0 = new NativeArrayIterator(nativeArrayBuffer0, nativeArrayBuffer0);
      Context context0 = Context.getCurrentContext();
      boolean boolean0 = nativeArrayIterator0.isDone(context0, nativeArrayBuffer0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ContextFactory contextFactory0 = ContextFactory.getGlobal();
      Context context0 = contextFactory0.enterContext();
      ScriptableObject scriptableObject0 = context0.initStandardObjects();
      NativeArrayIterator nativeArrayIterator0 = new NativeArrayIterator(scriptableObject0, scriptableObject0);
      ScriptableObject.getPropertyIds(nativeArrayIterator0);
      assertEquals("Array Iterator", nativeArrayIterator0.getClassName());
  }
}
