/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 02 03:20:11 GMT 2018
 */

package org.mozilla.javascript;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.mozilla.javascript.Context;
import org.mozilla.javascript.NativeStringIterator;
import org.mozilla.javascript.Scriptable;
import org.mozilla.javascript.ScriptableObject;
import org.mozilla.javascript.typedarrays.NativeArrayBuffer;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NativeStringIterator_ESTest extends NativeStringIterator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Context context0 = Context.enter();
      NativeArrayBuffer nativeArrayBuffer0 = new NativeArrayBuffer();
      Scriptable scriptable0 = context0.initStandardObjects((ScriptableObject) nativeArrayBuffer0);
      NativeStringIterator nativeStringIterator0 = new NativeStringIterator(scriptable0, nativeArrayBuffer0);
      String string0 = nativeStringIterator0.getClassName();
      assertEquals("String Iterator", string0);
  }
}
