/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 01 02:09:50 GMT 2018
 */

package org.mozilla.javascript.commonjs.module;

import org.junit.Test;
import static org.junit.Assert.*;
import java.net.URI;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockURI;
import org.junit.runner.RunWith;
import org.mozilla.javascript.Scriptable;
import org.mozilla.javascript.commonjs.module.ModuleScope;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ModuleScope_ESTest extends ModuleScope_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      URI uRI0 = MockURI.aFTPURI;
      ModuleScope moduleScope0 = new ModuleScope((Scriptable) null, (URI) null, uRI0);
      URI uRI1 = moduleScope0.getUri();
      assertNull(uRI1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      URI uRI0 = MockURI.aFTPURI;
      ModuleScope moduleScope0 = new ModuleScope((Scriptable) null, (URI) null, uRI0);
      URI uRI1 = moduleScope0.getBase();
      assertFalse(uRI1.isOpaque());
  }
}
