/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 01 02:10:39 GMT 2018
 */

package org.mozilla.javascript.commonjs.module;

import org.junit.Test;
import static org.junit.Assert.*;
import java.net.URI;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockURI;
import org.junit.runner.RunWith;
import org.mozilla.javascript.Script;
import org.mozilla.javascript.commonjs.module.ModuleScript;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ModuleScript_ESTest extends ModuleScript_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      URI uRI0 = MockURI.aFTPURI;
      ModuleScript moduleScript0 = new ModuleScript((Script) null, uRI0, uRI0);
      boolean boolean0 = moduleScript0.isSandboxed();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      URI uRI0 = MockURI.aFTPURI;
      ModuleScript moduleScript0 = new ModuleScript((Script) null, uRI0, uRI0);
      URI uRI1 = moduleScript0.getUri();
      assertSame(uRI1, uRI0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      URI uRI0 = MockURI.aFileURI;
      ModuleScript moduleScript0 = new ModuleScript((Script) null, uRI0, uRI0);
      Script script0 = moduleScript0.getScript();
      assertNull(script0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      URI uRI0 = MockURI.URI("msg.change.enumerable.with.configurable.false");
      ModuleScript moduleScript0 = new ModuleScript((Script) null, uRI0, uRI0);
      URI uRI1 = moduleScript0.getBase();
      assertFalse(uRI1.isOpaque());
  }
}
