/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 01 22:38:54 GMT 2018
 */

package org.mozilla.javascript.commonjs.module.provider;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.TreeSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.net.MockURI;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.evosuite.runtime.testdata.NetworkHandling;
import org.junit.runner.RunWith;
import org.mozilla.javascript.commonjs.module.provider.ModuleSource;
import org.mozilla.javascript.commonjs.module.provider.UrlConnectionExpiryCalculator;
import org.mozilla.javascript.commonjs.module.provider.UrlConnectionSecurityDomainProvider;
import org.mozilla.javascript.commonjs.module.provider.UrlModuleSourceProvider;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UrlModuleSourceProvider_ESTest extends UrlModuleSourceProvider_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UrlModuleSourceProvider urlModuleSourceProvider0 = new UrlModuleSourceProvider((Iterable<URI>) null, (Iterable<URI>) null);
      ModuleSource moduleSource0 = urlModuleSourceProvider0.loadFromPrivilegedLocations("Z+tx@Cs", (Object) null);
      assertNull(moduleSource0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<URI> linkedList0 = new LinkedList<URI>();
      URI uRI0 = MockURI.aFTPURI;
      linkedList0.add(uRI0);
      UrlModuleSourceProvider urlModuleSourceProvider0 = new UrlModuleSourceProvider(linkedList0, linkedList0);
      // Undeclared exception!
      try { 
        urlModuleSourceProvider0.loadFromPrivilegedLocations("org.mozilla.javascript.commonjs.module.provider.UrlModuleSourceProvider$URLValidator", (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.mozilla.javascript.commonjs.module.provider.UrlModuleSourceProvider", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://foo.barExpires.js");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "Expires");
      URI uRI0 = MockURI.aHttpURI;
      URI uRI1 = MockURI.resolve(uRI0, "Expires");
      TreeSet<URI> treeSet0 = new TreeSet<URI>();
      UrlConnectionSecurityDomainProvider urlConnectionSecurityDomainProvider0 = mock(UrlConnectionSecurityDomainProvider.class, new ViolatedAssumptionAnswer());
      doReturn(uRI1).when(urlConnectionSecurityDomainProvider0).getSecurityDomain(any(java.net.URLConnection.class));
      UrlModuleSourceProvider urlModuleSourceProvider0 = new UrlModuleSourceProvider(treeSet0, treeSet0, (UrlConnectionExpiryCalculator) null, urlConnectionSecurityDomainProvider0);
      ModuleSource moduleSource0 = urlModuleSourceProvider0.loadFromUri(uRI1, uRI0, (Object) null);
      assertNotNull(moduleSource0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ArrayList<URI> arrayList0 = new ArrayList<URI>();
      UrlModuleSourceProvider urlModuleSourceProvider0 = new UrlModuleSourceProvider(arrayList0, arrayList0);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://foo.barExpires.js");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "Expires");
      URI uRI0 = MockURI.aHttpURI;
      arrayList0.add(uRI0);
      ModuleSource moduleSource0 = urlModuleSourceProvider0.loadFromPrivilegedLocations("Expires", evoSuiteURL0);
      assertNotNull(moduleSource0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ArrayList<URI> arrayList0 = new ArrayList<URI>();
      UrlModuleSourceProvider urlModuleSourceProvider0 = new UrlModuleSourceProvider(arrayList0, arrayList0);
      boolean boolean0 = urlModuleSourceProvider0.entityNeedsRevalidation((Object) null);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LinkedList<URI> linkedList0 = new LinkedList<URI>();
      ArrayList<URI> arrayList0 = new ArrayList<URI>(linkedList0);
      UrlModuleSourceProvider urlModuleSourceProvider0 = new UrlModuleSourceProvider(arrayList0, arrayList0);
      ModuleSource moduleSource0 = urlModuleSourceProvider0.loadFromFallbackLocations("Expires", "Expires");
      URI uRI0 = MockURI.aHttpURI;
      try { 
        urlModuleSourceProvider0.loadFromActualUri(uRI0, uRI0, moduleSource0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Could not find: foo.bar
         //
         verifyException("org.evosuite.runtime.mock.java.net.EvoHttpURLConnection", e);
      }
  }
}
