/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 31 16:41:38 GMT 2018
 */

package org.mozilla.javascript.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.mozilla.javascript.ast.AstNode;
import org.mozilla.javascript.ast.IfStatement;
import org.mozilla.javascript.ast.Scope;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class IfStatement_ESTest extends IfStatement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement(0, (-2890));
      Scope scope0 = new Scope(19);
      ifStatement0.setCondition(scope0);
      StringBuilder stringBuilder0 = new StringBuilder();
      AstNode.DebugPrintVisitor astNode_DebugPrintVisitor0 = new AstNode.DebugPrintVisitor(stringBuilder0);
      // Undeclared exception!
      try { 
        ifStatement0.visit(astNode_DebugPrintVisitor0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.mozilla.javascript.ast.IfStatement", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement(0, 0);
      Scope scope0 = new Scope(19);
      scope0.setType(24);
      ifStatement0.setElsePart(scope0);
      assertEquals(1, scope0.depth());
      
      ifStatement0.setThenPart(scope0);
      ifStatement0.setCondition(scope0);
      String string0 = ifStatement0.toSource(1);
      assertEquals("  if ({\n}\n) \n    {\n  }\n  else \n    {\n  }\n", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement(0, 0);
      Scope scope0 = new Scope(19);
      ifStatement0.setElsePart(scope0);
      assertEquals(1, scope0.depth());
      
      ifStatement0.setThenPart(scope0);
      ifStatement0.setCondition(scope0);
      String string0 = ifStatement0.toSource(1);
      assertEquals("  if ({\n}\n) {\n  } else {\n  }\n", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement(0, (-2890));
      Scope scope0 = new Scope(19);
      ifStatement0.setThenPart(scope0);
      ifStatement0.setCondition(scope0);
      StringBuilder stringBuilder0 = new StringBuilder();
      AstNode.DebugPrintVisitor astNode_DebugPrintVisitor0 = new AstNode.DebugPrintVisitor(stringBuilder0);
      ifStatement0.visit(astNode_DebugPrintVisitor0);
      assertEquals("0\tIF 0 -2890\n19\t  BLOCK 19 1\n19\t  BLOCK 19 1\n", astNode_DebugPrintVisitor0.toString());
      assertEquals((-1), ifStatement0.getRp());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement();
      assertEquals((-1), ifStatement0.getRp());
      
      ifStatement0.setRp(0);
      assertEquals(0, ifStatement0.getRp());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement((-4137), (-4137));
      ifStatement0.setParens(1, 0);
      assertEquals(1, ifStatement0.getLp());
      assertEquals(0, ifStatement0.getRp());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement(0, (-2890));
      ifStatement0.setLp(41);
      assertEquals(41, ifStatement0.getLp());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement(0, (-2890));
      ifStatement0.setElsePosition(669);
      assertEquals(669, ifStatement0.getElsePosition());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement(0, (-2890));
      Scope scope0 = new Scope(19);
      ifStatement0.setElsePart(scope0);
      assertEquals(1, scope0.depth());
      
      ifStatement0.setThenPart(scope0);
      ifStatement0.setCondition(scope0);
      StringBuilder stringBuilder0 = new StringBuilder();
      AstNode.DebugPrintVisitor astNode_DebugPrintVisitor0 = new AstNode.DebugPrintVisitor(stringBuilder0);
      ifStatement0.visit(astNode_DebugPrintVisitor0);
      assertEquals("0\tIF 0 -2890\n19\t  BLOCK 19 1\n19\t  BLOCK 19 1\n19\t  BLOCK 19 1\n", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement((-4137), (-4137));
      ifStatement0.getThenPart();
      assertEquals((-1), ifStatement0.getElsePosition());
      assertEquals((-1), ifStatement0.getRp());
      assertEquals((-1), ifStatement0.getLp());
      assertEquals(113, ifStatement0.getType());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement();
      int int0 = ifStatement0.getRp();
      assertEquals((-1), ifStatement0.getLp());
      assertEquals(113, ifStatement0.getType());
      assertEquals((-1), int0);
      assertEquals((-1), ifStatement0.getElsePosition());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement();
      int int0 = ifStatement0.getLp();
      assertEquals((-1), ifStatement0.getElsePosition());
      assertEquals((-1), ifStatement0.getRp());
      assertEquals(113, ifStatement0.getType());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement();
      ifStatement0.getElsePart();
      assertEquals((-1), ifStatement0.getLp());
      assertEquals((-1), ifStatement0.getRp());
      assertEquals((-1), ifStatement0.getElsePosition());
      assertEquals(113, ifStatement0.getType());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement(0, (-2890));
      int int0 = ifStatement0.getElsePosition();
      assertEquals(113, ifStatement0.getType());
      assertEquals((-1), int0);
      assertEquals((-1), ifStatement0.getRp());
      assertEquals((-1), ifStatement0.getLp());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement(0);
      assertEquals((-1), ifStatement0.getElsePosition());
      assertEquals((-1), ifStatement0.getLp());
      assertEquals((-1), ifStatement0.getRp());
      assertEquals(113, ifStatement0.getType());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement();
      ifStatement0.getCondition();
      assertEquals((-1), ifStatement0.getRp());
      assertEquals((-1), ifStatement0.getElsePosition());
      assertEquals(113, ifStatement0.getType());
      assertEquals((-1), ifStatement0.getLp());
  }
}
