/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 31 16:39:19 GMT 2018
 */

package org.mozilla.javascript.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.mozilla.javascript.ast.ArrayComprehensionLoop;
import org.mozilla.javascript.ast.Block;
import org.mozilla.javascript.ast.ForInLoop;
import org.mozilla.javascript.ast.ForLoop;
import org.mozilla.javascript.ast.WhileLoop;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class Loop_ESTest extends Loop_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ForLoop forLoop0 = new ForLoop(1360, (-3427));
      forLoop0.setRp(11);
      assertEquals(11, forLoop0.getRp());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ArrayComprehensionLoop arrayComprehensionLoop0 = new ArrayComprehensionLoop(0);
      arrayComprehensionLoop0.setParens(0, 0);
      assertEquals(0, arrayComprehensionLoop0.getRp());
      assertEquals(0, arrayComprehensionLoop0.getLp());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      WhileLoop whileLoop0 = new WhileLoop();
      assertEquals((-1), whileLoop0.getLp());
      
      whileLoop0.setLp(0);
      assertEquals(0, whileLoop0.getLp());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ForInLoop forInLoop0 = new ForInLoop(459);
      int int0 = forInLoop0.getRp();
      assertEquals((-1), int0);
      assertEquals((-1), forInLoop0.getLp());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      WhileLoop whileLoop0 = new WhileLoop(0, 0);
      whileLoop0.getBody();
      assertEquals((-1), whileLoop0.getRp());
      assertEquals((-1), whileLoop0.getLp());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ForLoop forLoop0 = new ForLoop(0, 0);
      Block block0 = new Block();
      forLoop0.setBody(block0);
      assertEquals(0, forLoop0.getLength());
      assertEquals((-1), forLoop0.getLp());
      assertEquals((-1), forLoop0.getRp());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ArrayComprehensionLoop arrayComprehensionLoop0 = new ArrayComprehensionLoop();
      int int0 = arrayComprehensionLoop0.getLp();
      assertEquals((-1), int0);
      assertEquals((-1), arrayComprehensionLoop0.getRp());
  }
}
