/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 31 18:24:04 GMT 2018
 */

package org.mozilla.javascript.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.mozilla.javascript.Node;
import org.mozilla.javascript.ast.AstNode;
import org.mozilla.javascript.ast.XmlExpression;
import org.mozilla.javascript.ast.Yield;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class XmlExpression_ESTest extends XmlExpression_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Yield yield0 = new Yield();
      XmlExpression xmlExpression0 = new XmlExpression(1708, yield0);
      String string0 = xmlExpression0.toSource(3619);
      StringBuilder stringBuilder0 = new StringBuilder(string0);
      AstNode.DebugPrintVisitor astNode_DebugPrintVisitor0 = new AstNode.DebugPrintVisitor(stringBuilder0);
      xmlExpression0.visit(astNode_DebugPrintVisitor0);
      assertEquals(17, Node.NAME_PROP);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Yield yield0 = new Yield();
      XmlExpression xmlExpression0 = new XmlExpression(1708, yield0);
      xmlExpression0.setIsXmlAttribute(false);
      assertFalse(xmlExpression0.isXmlAttribute());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      XmlExpression xmlExpression0 = new XmlExpression(122, 122);
      assertEquals(1, Node.FUNCTION_PROP);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      XmlExpression xmlExpression0 = new XmlExpression(2742);
      boolean boolean0 = xmlExpression0.isXmlAttribute();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      XmlExpression xmlExpression0 = new XmlExpression();
      AstNode astNode0 = xmlExpression0.getExpression();
      assertNull(astNode0);
  }
}
