/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 31 16:41:09 GMT 2018
 */

package org.mozilla.javascript.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.mozilla.javascript.ast.AstNode;
import org.mozilla.javascript.ast.Name;
import org.mozilla.javascript.ast.RegExpLiteral;
import org.mozilla.javascript.ast.XmlElemRef;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class XmlElemRef_ESTest extends XmlElemRef_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      XmlElemRef xmlElemRef0 = new XmlElemRef(2640);
      RegExpLiteral regExpLiteral0 = new RegExpLiteral(15, 23);
      xmlElemRef0.setExpression(regExpLiteral0);
      StringBuilder stringBuilder0 = new StringBuilder();
      AstNode.DebugPrintVisitor astNode_DebugPrintVisitor0 = new AstNode.DebugPrintVisitor(stringBuilder0);
      xmlElemRef0.visit(astNode_DebugPrintVisitor0);
      assertEquals("2640\tREF_MEMBER 2640 1\n15\t  REGEXP -2625 23\n", astNode_DebugPrintVisitor0.toString());
      assertEquals("78", xmlElemRef0.toString());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      XmlElemRef xmlElemRef0 = new XmlElemRef(0);
      Name name0 = new Name(6);
      xmlElemRef0.setNamespace(name0);
      StringBuilder stringBuilder0 = new StringBuilder(2);
      AstNode.DebugPrintVisitor astNode_DebugPrintVisitor0 = new AstNode.DebugPrintVisitor(stringBuilder0);
      // Undeclared exception!
      try { 
        xmlElemRef0.visit(astNode_DebugPrintVisitor0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.mozilla.javascript.ast.XmlElemRef", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      XmlElemRef xmlElemRef0 = new XmlElemRef(1);
      Name name0 = new Name(2, 0, "");
      xmlElemRef0.setNamespace(name0);
      // Undeclared exception!
      try { 
        xmlElemRef0.toSource(20);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.mozilla.javascript.ast.XmlElemRef", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      XmlElemRef xmlElemRef0 = new XmlElemRef(2640);
      xmlElemRef0.atPos = 2640;
      // Undeclared exception!
      try { 
        xmlElemRef0.toSource(22);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.mozilla.javascript.ast.XmlElemRef", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      XmlElemRef xmlElemRef0 = new XmlElemRef(0);
      xmlElemRef0.setRb(22);
      assertEquals(22, xmlElemRef0.getRb());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      XmlElemRef xmlElemRef0 = new XmlElemRef();
      xmlElemRef0.setLb(3492);
      assertEquals(3492, xmlElemRef0.getLb());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      XmlElemRef xmlElemRef0 = new XmlElemRef(2640);
      RegExpLiteral regExpLiteral0 = new RegExpLiteral(15, 23);
      xmlElemRef0.setExpression(regExpLiteral0);
      String string0 = xmlElemRef0.toSource(22);
      assertEquals((-1), xmlElemRef0.getLb());
      assertEquals("                                            [/null/]", string0);
      assertEquals((-1), xmlElemRef0.getRb());
      assertEquals(78, xmlElemRef0.getType());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      XmlElemRef xmlElemRef0 = new XmlElemRef();
      xmlElemRef0.setBrackets(2, 1474);
      assertEquals(2, xmlElemRef0.getLb());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      XmlElemRef xmlElemRef0 = new XmlElemRef();
      int int0 = xmlElemRef0.getRb();
      assertEquals((-1), xmlElemRef0.getLb());
      assertEquals((-1), int0);
      assertEquals("78", xmlElemRef0.toString());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      XmlElemRef xmlElemRef0 = new XmlElemRef(337, 337);
      assertEquals((-1), xmlElemRef0.getRb());
      assertEquals((-1), xmlElemRef0.getLb());
      assertEquals(78, xmlElemRef0.getType());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      XmlElemRef xmlElemRef0 = new XmlElemRef();
      int int0 = xmlElemRef0.getLb();
      assertEquals((-1), int0);
      assertEquals("78", xmlElemRef0.toString());
      assertEquals((-1), xmlElemRef0.getRb());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      XmlElemRef xmlElemRef0 = new XmlElemRef(0);
      xmlElemRef0.getExpression();
      assertEquals((-1), xmlElemRef0.getRb());
      assertEquals(78, xmlElemRef0.getType());
      assertEquals((-1), xmlElemRef0.getLb());
  }
}
