/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 02 05:30:48 GMT 2018
 */

package org.mozilla.classfile;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.mozilla.classfile.ClassFileWriter;
import org.mozilla.classfile.ConstantPool;
import org.mozilla.classfile.SuperBlock;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SuperBlock_ESTest extends SuperBlock_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      int[] intArray0 = new int[2];
      SuperBlock superBlock0 = new SuperBlock(0, 0, 0, intArray0);
      String string0 = superBlock0.toString();
      assertEquals("sb 0", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int[] intArray0 = new int[3];
      SuperBlock superBlock0 = new SuperBlock(38, 38, (-3458), intArray0);
      superBlock0.setInQueue(true);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int[] intArray0 = new int[3];
      SuperBlock superBlock0 = new SuperBlock((-1453), (-1453), (-1453), intArray0);
      int[] intArray1 = new int[4];
      intArray1[0] = 3;
      ClassFileWriter classFileWriter0 = new ClassFileWriter("", "", " is not offset of tableswitch statement");
      ConstantPool constantPool0 = new ConstantPool(classFileWriter0);
      superBlock0.merge(intArray1, 3, intArray0, 3, constantPool0);
      boolean boolean0 = superBlock0.merge(intArray0, 3, intArray0, 3, (ConstantPool) null);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int[] intArray0 = new int[0];
      SuperBlock superBlock0 = new SuperBlock((-1442), (-1442), (-1442), intArray0);
      superBlock0.setInitialized(true);
      // Undeclared exception!
      try { 
        superBlock0.merge(intArray0, (-1442), intArray0, 0, (ConstantPool) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // bad merge attempt
         //
         verifyException("org.mozilla.classfile.SuperBlock", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int[] intArray0 = new int[2];
      SuperBlock superBlock0 = new SuperBlock(0, 0, 0, intArray0);
      boolean boolean0 = superBlock0.isInitialized();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int[] intArray0 = new int[2];
      SuperBlock superBlock0 = new SuperBlock((-122), (-122), 628, intArray0);
      boolean boolean0 = superBlock0.isInQueue();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int[] intArray0 = new int[6];
      intArray0[0] = (int) (short)4;
      SuperBlock superBlock0 = new SuperBlock((short)1, (short)64, (short)16, intArray0);
      int[] intArray1 = superBlock0.getTrimmedLocals();
      assertArrayEquals(new int[] {4}, intArray1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int[] intArray0 = new int[0];
      SuperBlock superBlock0 = new SuperBlock(0, 1951, 0, intArray0);
      int int0 = superBlock0.getStart();
      assertEquals(1951, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      int[] intArray0 = new int[1];
      SuperBlock superBlock0 = new SuperBlock(912, 912, 912, intArray0);
      int[] intArray1 = superBlock0.getStack();
      assertEquals(0, intArray1.length);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int[] intArray0 = new int[3];
      SuperBlock superBlock0 = new SuperBlock((-221), (-652), 0, intArray0);
      int[] intArray1 = superBlock0.getLocals();
      assertArrayEquals(new int[] {0, 0, 0}, intArray1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      int[] intArray0 = new int[0];
      SuperBlock superBlock0 = new SuperBlock((-3441), (-612), 0, intArray0);
      int int0 = superBlock0.getIndex();
      assertEquals((-3441), int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      int[] intArray0 = new int[5];
      SuperBlock superBlock0 = new SuperBlock(1707, 1707, (-2172), intArray0);
      int int0 = superBlock0.getEnd();
      assertEquals((-2172), int0);
  }
}
