/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 02 15:52:09 GMT 2018
 */

package org.mozilla.javascript.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.mozilla.javascript.Token;
import org.mozilla.javascript.ast.Comment;
import org.mozilla.javascript.ast.IfStatement;
import org.mozilla.javascript.ast.Label;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IfStatement_ESTest extends IfStatement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement();
      Label label0 = new Label();
      Token.CommentType token_CommentType0 = Token.CommentType.LINE;
      Comment comment0 = new Comment(4, 4, token_CommentType0, "");
      ifStatement0.setElsePart(label0);
      assertEquals(0, label0.getPosition());
      
      ifStatement0.setThenPart(label0);
      ifStatement0.setCondition(comment0);
      String string0 = ifStatement0.debugPrint();
      assertEquals("-1\tIF -1 1\n4\t  COMMENT 5 4\n-1\t  LABEL 0 1\n-1\t  LABEL 0 1\n", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement();
      Label label0 = new Label(19, 1);
      Token.CommentType token_CommentType0 = Token.CommentType.BLOCK_COMMENT;
      Comment comment0 = new Comment(4, 4, token_CommentType0, ",)!23X27");
      label0.setType(130);
      ifStatement0.setElsePart(label0);
      ifStatement0.setThenPart(label0);
      ifStatement0.setCondition(comment0);
      String string0 = ifStatement0.toSource(24);
      assertEquals("                                                if (,)!23X27) null: else null:\n", string0);
      assertEquals("113", ifStatement0.toString());
      assertEquals((-1), ifStatement0.getRp());
      assertEquals((-1), ifStatement0.getLp());
      assertEquals((-1), ifStatement0.getElsePosition());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement();
      Label label0 = new Label();
      Token.CommentType token_CommentType0 = Token.CommentType.LINE;
      Comment comment0 = new Comment(4, 4, token_CommentType0, "");
      ifStatement0.setElsePart(label0);
      assertEquals(0, label0.getPosition());
      
      ifStatement0.setThenPart(label0);
      ifStatement0.setCondition(comment0);
      String string0 = ifStatement0.toSource();
      assertEquals("if () \n  null:\nelse \n  null:\n", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement(3499, 3499);
      ifStatement0.setRp(5);
      assertEquals(5, ifStatement0.getRp());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement();
      ifStatement0.setParens(0, 950);
      assertEquals(950, ifStatement0.getRp());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement(3499, 3499);
      ifStatement0.setLp((-2434));
      assertEquals((-2434), ifStatement0.getLp());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement(0, 0);
      ifStatement0.setElsePosition(102);
      assertEquals(102, ifStatement0.getElsePosition());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement();
      ifStatement0.getThenPart();
      assertEquals((-1), ifStatement0.getLp());
      assertEquals("113", ifStatement0.toString());
      assertEquals((-1), ifStatement0.getElsePosition());
      assertEquals((-1), ifStatement0.getRp());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement();
      int int0 = ifStatement0.getRp();
      assertEquals((-1), ifStatement0.getElsePosition());
      assertEquals("113", ifStatement0.toString());
      assertEquals((-1), int0);
      assertEquals((-1), ifStatement0.getLp());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement();
      int int0 = ifStatement0.getLp();
      assertEquals(113, ifStatement0.getType());
      assertEquals((-1), int0);
      assertEquals((-1), ifStatement0.getRp());
      assertEquals((-1), ifStatement0.getElsePosition());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement();
      ifStatement0.getElsePart();
      assertEquals((-1), ifStatement0.getRp());
      assertEquals((-1), ifStatement0.getElsePosition());
      assertEquals((-1), ifStatement0.getLp());
      assertEquals("113", ifStatement0.toString());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement(3499, 3499);
      int int0 = ifStatement0.getElsePosition();
      assertEquals((-1), int0);
      assertEquals(113, ifStatement0.getType());
      assertEquals((-1), ifStatement0.getLp());
      assertEquals((-1), ifStatement0.getRp());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement(77);
      assertEquals((-1), ifStatement0.getRp());
      assertEquals((-1), ifStatement0.getLp());
      assertEquals((-1), ifStatement0.getElsePosition());
      assertEquals("113", ifStatement0.toString());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      IfStatement ifStatement0 = new IfStatement();
      ifStatement0.getCondition();
      assertEquals((-1), ifStatement0.getRp());
      assertEquals((-1), ifStatement0.getLp());
      assertEquals(113, ifStatement0.getType());
      assertEquals((-1), ifStatement0.getElsePosition());
  }
}
