/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 01 14:01:22 GMT 2018
 */

package org.mozilla.javascript;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.mozilla.javascript.Context;
import org.mozilla.javascript.InterpretedFunction;
import org.mozilla.javascript.InterpreterData;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Arguments_ESTest extends Arguments_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      InterpreterData interpreterData0 = new InterpreterData(2549, "org.mozilla.javascript.Arguments$ThrowTypeError", "org.mozilla.javascript.Arguments$ThrowTypeError", false);
      interpreterData0.argCount = 1;
      interpreterData0.argNames = interpreterData0.itsStringTable;
      // Undeclared exception!
      try { 
        InterpretedFunction.createScript(interpreterData0, (Object) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // No Context associated with current Thread
         //
         verifyException("org.mozilla.javascript.Context", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      InterpreterData interpreterData0 = new InterpreterData(2549, "org.mozilla.javascript.Arguments$ThrowTypeError", "org.mozilla.javascript.Arguments$ThrowTypeError", false);
      interpreterData0.argCount = 2;
      interpreterData0.argNames = interpreterData0.itsStringTable;
      // Undeclared exception!
      try { 
        InterpretedFunction.createScript(interpreterData0, (Object) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // No Context associated with current Thread
         //
         verifyException("org.mozilla.javascript.Context", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      InterpreterData interpreterData0 = new InterpreterData(2549, "org.mozilla.javascript.Arguments$ThrowTypeError", "org.mozilla.javascript.Arguments$ThrowTypeError", true);
      boolean[] booleanArray0 = new boolean[4];
      interpreterData0.argIsConst = booleanArray0;
      interpreterData0.argNames = interpreterData0.itsStringTable;
      // Undeclared exception!
      try { 
        InterpretedFunction.createScript(interpreterData0, (Object) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // No Context associated with current Thread
         //
         verifyException("org.mozilla.javascript.Context", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      InterpreterData interpreterData0 = new InterpreterData(2549, "org.mozilla.javascript.Arguments$hrowTypeError", "org.mozilla.javascript.Arguments$hrowTypeError", false);
      boolean[] booleanArray0 = new boolean[29];
      interpreterData0.argIsConst = booleanArray0;
      interpreterData0.argNames = interpreterData0.itsStringTable;
      // Undeclared exception!
      try { 
        InterpretedFunction.createScript(interpreterData0, (Object) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // No Context associated with current Thread
         //
         verifyException("org.mozilla.javascript.Context", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      InterpreterData interpreterData0 = new InterpreterData(0, "org.mozilla.javascript.Arguments$ThrowTypeError", "org.mozilla.javascript.Arguments$ThrowTypeError", false);
      boolean[] booleanArray0 = new boolean[22];
      interpreterData0.argIsConst = booleanArray0;
      String[] stringArray0 = new String[17];
      interpreterData0.argNames = stringArray0;
      // Undeclared exception!
      try { 
        InterpretedFunction.createScript(interpreterData0, (Object) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // No Context associated with current Thread
         //
         verifyException("org.mozilla.javascript.Context", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      InterpreterData interpreterData0 = new InterpreterData(2549, "org.mozilla.j~vascript.Arguments$ThrowTypeError", "org.mozilla.j~vascript.Arguments$ThrowTypeError", true);
      boolean[] booleanArray0 = new boolean[6];
      interpreterData0.argIsConst = booleanArray0;
      String[] stringArray0 = new String[9];
      interpreterData0.argNames = stringArray0;
      // Undeclared exception!
      try { 
        InterpretedFunction.createScript(interpreterData0, (Object) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // No Context associated with current Thread
         //
         verifyException("org.mozilla.javascript.Context", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      InterpreterData interpreterData0 = new InterpreterData(2549, "org.mozilla.javascript.Arguments$ThrowTypeError", "org.mozilla.javascript.Arguments$ThrowTypeError", false);
      boolean[] booleanArray0 = new boolean[6];
      interpreterData0.argIsConst = booleanArray0;
      String[] stringArray0 = new String[9];
      interpreterData0.argNames = stringArray0;
      // Undeclared exception!
      try { 
        InterpretedFunction.createScript(interpreterData0, (Object) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // No Context associated with current Thread
         //
         verifyException("org.mozilla.javascript.Context", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      InterpreterData interpreterData0 = new InterpreterData(2549, "org.mozilla.javascript.Arguments$ThrowTypeError", "org.mozilla.javascript.Arguments$ThrowTypeError", false);
      boolean[] booleanArray0 = new boolean[5];
      interpreterData0.argIsConst = booleanArray0;
      interpreterData0.argNames = interpreterData0.itsStringTable;
      // Undeclared exception!
      try { 
        InterpretedFunction.createScript(interpreterData0, (Object) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // No Context associated with current Thread
         //
         verifyException("org.mozilla.javascript.Context", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      InterpreterData interpreterData0 = new InterpreterData(2549, "org.mozilla.javascript.Arguments$ThrowTypeError", "org.mozilla.javascript.Arguments$ThrowTypeError", false);
      boolean[] booleanArray0 = new boolean[6];
      interpreterData0.argIsConst = booleanArray0;
      interpreterData0.argNames = interpreterData0.itsStringTable;
      // Undeclared exception!
      try { 
        InterpretedFunction.createScript(interpreterData0, (Object) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // No Context associated with current Thread
         //
         verifyException("org.mozilla.javascript.Context", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      InterpreterData interpreterData0 = new InterpreterData((-517), "org.mozilla.javascript.Arguments$ThrowTypeError", "org.mozilla.javascript.Arguments$ThrowTypeError", false);
      String[] stringArray0 = new String[13];
      interpreterData0.argNames = stringArray0;
      // Undeclared exception!
      try { 
        InterpretedFunction.createScript(interpreterData0, (Object) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // No Context associated with current Thread
         //
         verifyException("org.mozilla.javascript.Context", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Context.getCurrentContext();
  }
}
