/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 01 22:32:45 GMT 2018
 */

package org.mozilla.javascript.commonjs.module;

import org.junit.Test;
import static org.junit.Assert.*;
import java.net.URI;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockURI;
import org.junit.runner.RunWith;
import org.mozilla.javascript.Scriptable;
import org.mozilla.javascript.commonjs.module.ModuleScope;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ModuleScope_ESTest extends ModuleScope_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      URI uRI0 = MockURI.URI("org.mozilla.javascript.commonjs.module.ModuleScope", "-sgT7l`gOT", "\"P+VK{*:JCe_W<Tb");
      ModuleScope moduleScope0 = new ModuleScope((Scriptable) null, uRI0, uRI0);
      URI uRI1 = moduleScope0.getUri();
      assertNull(uRI1.getHost());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      URI uRI0 = MockURI.URI("org.mozilla.javascript.commonjs.module.ModuleScope", "-sgT7l`gOT", "\"P+VK{*:JCe_W<Tb");
      ModuleScope moduleScope0 = new ModuleScope((Scriptable) null, uRI0, uRI0);
      URI uRI1 = moduleScope0.getBase();
      assertSame(uRI1, uRI0);
  }
}
