/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 02 18:20:12 GMT 2018
 */

package org.mozilla.javascript.regexp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.mozilla.javascript.regexp.SubString;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SubString_ESTest extends SubString_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SubString subString0 = new SubString("M+Lba$p", 0, 921);
      // Undeclared exception!
      try { 
        subString0.toString();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SubString subString0 = new SubString("");
      assertEquals("", subString0.toString());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SubString subString0 = new SubString();
      assertEquals("", subString0.toString());
  }
}
